VIEW_PLAYER = "view player"
INVENTORY = "Inventory"
EQUIPMENT = "equipment"
USE_ITEMS = "use items"
SAVE_GAME = "save game"
CONSUME_ITEMS = "consume items"
REMOVE_ITEMS = "unequip items"
SELL_ITEMS = "sell items"
VIEW_ATTACK = "view attack"
VIEW_STATS = "view stats"

EQUIPPABLE = "EQUIPPABLE"
CONSUMABLE = "CONSUMABLE"

BLACK_MARKET = "black market"
BUY_ITEMS = "buy items"
COUNT_ITENS = "count items"

PLAY = "Play"
LOAD = "Load"
QUIT = "Quit"
BACK = "back"
NEXT = "next"
GO_BACK = "go back"
EXIT = "exit"

BATTLE_ATTACK = "attack"
BATTLE_FLED = "fled"
BATTLE_WIN = "win"
BATTLE_LOSE = "lose"
BATTLE_TURN_COMMANDS = [BATTLE_ATTACK, USE_ITEMS, BATTLE_FLED]